# Generated by Django 5.0.2 on 2024-03-07 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_post_sub_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='is_solved',
            field=models.BooleanField(default=True),
        ),
    ]
